server:
  port: 8080

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: member
          uri: http://member-service:8080
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1
        - id: point
          uri: http://point-service:8080
          predicates:
            - Path=/point/**
          filters:
            - StripPrefix=1
        - id: notification
          uri: http://notification-service:8080
          predicates:
            - Path=/notification/**
          filters:
            - StripPrefix=1
        - id: product
          uri: http://product-service:8080
          predicates:
            - Path=/product/**
          filters:
            - StripPrefix=1
      default-filters:
        - AddResponseHeader=X-Gateway, v1
management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true
