spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id : member
          uri : lb://member-service
          predicates:
            - Path=/member/**         # 게이트웨이에서 받는 경로
          filters:
            - StripPrefix=1            # /member 제거 후 전달
        - id: point
          uri: lb://point-service
          predicates:
            - Path=/point/**         # 게이트웨이에서 받는 경로
          filters:
            - StripPrefix=1            # /member 제거 후 전달
        - id: notification
          uri: lb://notification-service
          predicates:
            - Path=/notification/**         # 게이트웨이에서 받는 경로
          filters:
            - StripPrefix=1            # /member 제거 후 전달
        - id: product
          uri: lb://product-service
          predicates:
            - Path=/product/**         # 게이트웨이에서 받는 경로
          filters:
            - StripPrefix=1            # /member 제거 후 전달
  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWAyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 1800
      refresh-token-validity-in-seconds: 604800
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
