server:
  port: 8083

spring:
  application:
    name: point-service
  datasource:
    url: jdbc:mariadb://mariadb:3306/point_db
    username: point_user
    password: point_pw
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  kafka:
    bootstrap-servers: kafka:29092
    consumer:
      group-id: point-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.store.common.event"
    listener:
      missing-topics-fatal: false

api:
  prefix: "/api/v1"

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
