apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: msa

resources:
  - zookeeper.yaml
  - kafka.yaml
  - redis.yaml
  - mariadb-member.yaml
  - mariadb-point.yaml
  - mariadb-product.yaml

configMapGenerator:
  # ── 앱별 공개 설정 (URL/프로필 등)
  - name: member-config
    literals:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-member:3306/member_db?connectTimeout=5000&socketTimeout=10000&useUnicode=true&characterEncoding=UTF-8
  - name: point-config
    literals:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-point:3306/point_db?connectTimeout=5000&socketTimeout=10000&useUnicode=true&characterEncoding=UTF-8
  - name: product-config
    literals:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb-product:3306/product_db?connectTimeout=5000&socketTimeout=10000&useUnicode=true&characterEncoding=UTF-8
  - name: notification-config
    literals:
      - SPRING_PROFILES_ACTIVE=prod

secretGenerator:
  # ── DB 비밀값(서비스별 DB 사용자/비밀번호)
  - name: mariadb-member-secret
    literals:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=member_db
      - MYSQL_USER=member_user
      - MYSQL_PASSWORD=member_pw
  - name: mariadb-point-secret
    literals:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=point_db
      - MYSQL_USER=point_user
      - MYSQL_PASSWORD=point_pw
  - name: mariadb-product-secret
    literals:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=product_db
      - MYSQL_USER=product_user
      - MYSQL_PASSWORD=product_pw

  # ── (선택) 앱 자체의 비밀값(JWT 등)
  - name: member-app-secret
    literals:
      - JWT_SECRET=change_me
  - name: point-app-secret
    literals:
      - JWT_SECRET=change_me
  - name: product-app-secret
    literals:
      - JWT_SECRET=change_me

generatorOptions:
  disableNameSuffixHash: true
