apiVersion: v1
kind: Service
metadata:
  name: product-db
  namespace: msa
spec:
  selector:
    app: product-db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: product-db
  namespace: msa
spec:
  serviceName: product-db
  replicas: 1
  selector:
    matchLabels:
      app: product-db
  template:
    metadata:
      labels:
        app: product-db
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.0.2
          ports:
            - name: mysql
              containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-product-secret
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: mariadb-product-secret
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-product-secret
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-product-secret
                  key: MYSQL_PASSWORD
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          # mariadb-* StatefulSet 컨테이너에 추가
          startupProbe:
            tcpSocket:
              port: 3306
            # 초기화가 오래 걸려도 충분히 기다리기 (예: 최대 5분)
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 60   # 60 * 5s = 300초
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command: [ "sh","-c","pidof mysqld || pidof mariadbd" ]
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: data
          emptyDir: {}
