apiVersion: v1
kind: Service
metadata:
  name: mariadb-point
  labels: { app: mariadb-point }
spec:
  clusterIP: None
  selector: { app: mariadb-point }
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-point
spec:
  serviceName: mariadb-point
  replicas: 1
  selector:
    matchLabels: { app: mariadb-point }
  template:
    metadata:
      labels: { app: mariadb-point }
    spec:
      containers:
        - name: mariadb
          image: mariadb:11.0
          ports:
            - containerPort: 3306
          envFrom:
            - secretRef: { name: mariadb-point-secret }   # MYSQL_* 사용
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          readinessProbe:
            tcpSocket: { port: 3306 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket: { port: 3306 }
            initialDelaySeconds: 15
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 10Gi
