# src/main/resources/application-local.yml
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/mydb
    username: root
    password: ab12cd34!
  redis:
    host: localhost
    port: 6379
    password: ab12cd34!   # 보안 설정한 경우 추가
    timeout: 2000

server:
  port: 8080

kisa:
  mid: kistest00m
  merchantKey: 2d6ECGhR1pg/1QGE1lcRI4awsWEgshjEyI8UgYslLPJSuNeyPTkdrT8XWARezvDTUJClWQWhjxzBbu7AsuLZqg==
  payReturnUrl: "${api.prefix}/order/callback"
  cancelReturnUrl: "${api.prefix}/order/cancelCallback"
  apiUrl: "https://testapi.kispg.co.kr"
  currencyType: KRW
  model: WEB

file:
  upload-path: C:\uploads
