# spring setting
spring:
  profiles:
    active: prd
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false  # 개발 시 변경 사항 즉시 반영
  datasource:
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
  redis:
    host: 3.35.20.58
    port: 6379
    password: jtocean   # 보안 설정한 경우 추가
    timeout: 2000
  jpa:
    hibernate:
      ddl-auto: update #validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true  # SQL pretty print
        use_sql_comments: false
        id:
          new_generator_mappings: false
    database-platform: org.hibernate.dialect.MariaDBDialect
  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 1800
      refresh-token-validity-in-seconds: 604800
  mvc:
    throw-exception-if-no-handler-found=true: true
  servlet:
    multipart:
      max-file-size: 50MB       # 단일 파일 업로드 최대 크기
      max-request-size: 100MB    # 전체 요청(모든 파트 합산) 최대 크기

server:
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: false
    include-binding-errors: always
    path: /error
  tomcat:
    max-swallow-size: 100MB     # Tomcat 9 이상에서 POST body 최대 크기

api:
  prefix: "/api/v1"

encryptor:
  key: jtocean

logging:
  level:
    org.springframework.web.servlet: TRACE

security:
  exclude-urls:
    - /auth/login
    - /member/signup
    - /product
    - /js
    - /css

