server:
  port: 8081

spring:
  profiles:
    active: local
  application:
    name: member-service
  datasource:
    url: jdbc:mariadb://localhost:3306/member_db
    username: member_user
    password: member_pw
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect
  data:
    redis:
      host: redis
      port: 6379
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.store.common.event"
    listener:
      missing-topics-fatal: false

  security:
    jwt:
      header: Authorization
      secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWAyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
      token-validity-in-seconds: 1800
      refresh-token-validity-in-seconds: 604800

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

api:
  prefix: "/api/v1"

encryptor:
  key: min

security:
  exclude-urls:
    - /member/signup
    - /auth/login
