apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway:1.0.0   # ← 실제 이미지로 교체
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: SPRING_CLOUD_GATEWAY_DISCOVERY_LOCATOR_ENABLED
              value: "false"
            - name: SPRING_CLOUD_DISCOVERY_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_ENABLED
              value: "false"
            - name: EUREKA_CLIENT_REGISTER_WITH_EUREKA
              value: "false"
            - name: EUREKA_CLIENT_FETCH_REGISTRY
              value: "false"
          startupProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            periodSeconds: 3
            failureThreshold: 60   # ~3분 대기
          readinessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            periodSeconds: 5
            initialDelaySeconds: 5
            failureThreshold: 12
          livenessProbe:
            httpGet: { path: /actuator/health, port: 8080 }
            periodSeconds: 10
            initialDelaySeconds: 120
            failureThreshold: 3
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
